name: "🚀 Demande de fabrication pièce"
description: "Demande de refabrication d'une pièce 3D."
title: "Demande fabrication: [Nom de la pièce]"
labels:
  - demande
  - fabrication
assignees:
  - tonusername

body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir ce formulaire pour demander la fabrication d'une pièce.

  - type: input
    id: nom_piece
    attributes:
      label: Nom / référence de la pièce
      description: 'Exemples : Poignee lave-linge X, Piece aspirateur Y, etc.'
      placeholder: "Nom ou référence de la pièce"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description détaillée
      description: 'Dimensions approximatives, rôle de la pièce, emplacement, etc.'
      placeholder: "Décrivez la pièce et son utilisation..."
    validations:
      required: true

  - type: textarea
    id: photos
    attributes:
      label: Photos / liens
      description: 'Ajoutez des photos ou liens vers des images de la pièce.'
      placeholder: "Coller ici des liens ou joindre des images."
    validations:
      required: true

  - type: input
    id: quantite
    attributes:
      label: Quantité souhaitée
      placeholder: "1"
    validations:
      required: true
