name: "Soumission de pièce introuvable"
description: "Proposer une pièce à refabriquer en impression 3D"
title: "[Soumission] Nom de la pièce"
labels: ["soumission"]
body:
  - type: input
    attributes:
      label: Nom de la pièce
      placeholder: Ex: Clip de porte
    validations:
      required: true

  - type: input
    attributes:
      label: Appareil / Objet concerné
      placeholder: Ex: Lave-vaisselle Bosch Série X
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description de la fonction de la pièce
      placeholder: À quoi sert-elle ?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Pourquoi la pièce est introuvable ?
      placeholder: Arrêt de production, SAV indisponible, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Photos / documents
      placeholder: Liens vers images, scans, dimensions
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Accord
      options:
        - label: J’accepte que ReFab3D refabrique et commercialise cette pièce
          required: true
